keep_joints:
  - x_taxel_01_uSPa44_01_joint
  - x_taxel_01_uSPa44_02_joint
  - x_taxel_01_uSPa44_03_joint
  - x_taxel_01_uSPa44_04_joint
  - x_taxel_01_uSPa44_05_joint
  - x_taxel_01_uSPa44_06_joint
  - x_taxel_01_uSPa44_07_joint
  - x_taxel_01_uSPa44_08_joint
  - x_taxel_01_uSPa44_09_joint
  - x_taxel_01_uSPa44_10_joint
  - x_taxel_01_uSPa44_11_joint
  - x_taxel_01_uSPa44_12_joint
  - x_taxel_01_uSPa44_13_joint
  - x_taxel_01_uSPa44_14_joint
  - x_taxel_01_uSPa44_15_joint
  - x_taxel_01_uSPa44_16_joint
  - x_taxel_02_uSPa44_01_joint
  - x_taxel_02_uSPa44_02_joint
  - x_taxel_02_uSPa44_03_joint
  - x_taxel_02_uSPa44_04_joint
  - x_taxel_02_uSPa44_05_joint
  - x_taxel_02_uSPa44_06_joint
  - x_taxel_02_uSPa44_07_joint
  - x_taxel_02_uSPa44_08_joint
  - x_taxel_02_uSPa44_09_joint
  - x_taxel_02_uSPa44_10_joint
  - x_taxel_02_uSPa44_11_joint
  - x_taxel_02_uSPa44_12_joint
  - x_taxel_02_uSPa44_13_joint
  - x_taxel_02_uSPa44_14_joint
  - x_taxel_02_uSPa44_15_joint
  - x_taxel_02_uSPa44_16_joint
