server_model_joint_map:
  0: x_taxel_0_f3_dg5f_ft_09_joint
  1: x_taxel_0_f3_dg5f_ft_08_joint
  2: x_taxel_0_f2_dg5f_ft_09_joint
  3: x_taxel_0_f2_dg5f_ft_08_joint
  4: x_taxel_0_f3_dg5f_ft_11_joint
  5: x_taxel_0_f3_dg5f_ft_06_joint
  6: x_taxel_0_f3_dg5f_ft_07_joint
  7: x_taxel_0_f3_dg5f_ft_03_joint
  8: x_taxel_0_f4_dg5f_ft_09_joint
  9: x_taxel_0_f4_dg5f_ft_08_joint
  10: x_taxel_0_f2_dg5f_ft_11_joint
  11: x_taxel_0_f2_dg5f_ft_06_joint
  12: x_taxel_0_f2_dg5f_ft_07_joint
  13: x_taxel_0_f2_dg5f_ft_03_joint
  14: x_taxel_0_f3_dg5f_ft_12_joint
  15: x_taxel_0_f3_dg5f_ft_10_joint
  16: x_taxel_0_f3_dg5f_ft_05_joint
  17: x_taxel_0_f3_dg5f_ft_04_joint
  18: x_taxel_0_f3_dg5f_ft_02_joint
  19: x_taxel_0_f3_dg5f_ft_01_joint
  20: x_taxel_0_f4_dg5f_ft_11_joint
  21: x_taxel_0_f4_dg5f_ft_06_joint
  22: x_taxel_0_f4_dg5f_ft_07_joint
  23: x_taxel_0_f4_dg5f_ft_03_joint
  24: x_taxel_0_f5_dg5f_ft_09_joint
  25: x_taxel_0_f5_dg5f_ft_08_joint
  26: x_taxel_0_f2_dg5f_ft_12_joint
  27: x_taxel_0_f2_dg5f_ft_10_joint
  28: x_taxel_0_f2_dg5f_ft_05_joint
  29: x_taxel_0_f2_dg5f_ft_04_joint
  30: x_taxel_0_f2_dg5f_ft_02_joint
  31: x_taxel_0_f2_dg5f_ft_01_joint
  32: x_taxel_0_f4_dg5f_ft_12_joint
  33: x_taxel_0_f4_dg5f_ft_10_joint
  34: x_taxel_0_f4_dg5f_ft_05_joint
  35: x_taxel_0_f4_dg5f_ft_04_joint
  36: x_taxel_0_f4_dg5f_ft_02_joint
  37: x_taxel_0_f4_dg5f_ft_01_joint
  38: x_taxel_0_f5_dg5f_ft_11_joint
  39: x_taxel_0_f5_dg5f_ft_06_joint
  40: x_taxel_0_f5_dg5f_ft_07_joint
  41: x_taxel_0_f5_dg5f_ft_03_joint
  42: x_taxel_0_f3_mid_uSPa22_03_joint
  43: x_taxel_0_f3_mid_uSPa22_04_joint
  44: x_taxel_0_f5_dg5f_ft_12_joint
  45: x_taxel_0_f5_dg5f_ft_10_joint
  46: x_taxel_0_f5_dg5f_ft_05_joint
  47: x_taxel_0_f5_dg5f_ft_04_joint
  48: x_taxel_0_f5_dg5f_ft_02_joint
  49: x_taxel_0_f5_dg5f_ft_01_joint
  50: x_taxel_0_f2_mid_uSPa22_03_joint
  51: x_taxel_0_f2_mid_uSPa22_04_joint
  52: x_taxel_0_f3_mid_uSPa22_01_joint
  53: x_taxel_0_f3_mid_uSPa22_02_joint
  54: x_taxel_0_f4_mid_uSPa22_03_joint
  55: x_taxel_0_f4_mid_uSPa22_04_joint
  56: x_taxel_0_f2_mid_uSPa22_01_joint
  57: x_taxel_0_f2_mid_uSPa22_02_joint
  58: x_taxel_0_f4_mid_uSPa22_01_joint
  59: x_taxel_0_f4_mid_uSPa22_02_joint
  60: x_taxel_0_f5_mid_uSPa22_03_joint
  61: x_taxel_0_f5_mid_uSPa22_04_joint
  62: x_taxel_0_f1_dg5f_ft_09_joint
  63: x_taxel_0_f1_dg5f_ft_08_joint
  64: x_taxel_0_f3_prox_uSPa22_03_joint
  65: x_taxel_0_f3_prox_uSPa22_04_joint
  66: x_taxel_0_f5_mid_uSPa22_01_joint
  67: x_taxel_0_f5_mid_uSPa22_02_joint
  68: x_taxel_0_f1_dg5f_ft_11_joint
  69: x_taxel_0_f1_dg5f_ft_06_joint
  70: x_taxel_0_f1_dg5f_ft_07_joint
  71: x_taxel_0_f1_dg5f_ft_03_joint
  72: x_taxel_0_f2_prox_uSPa22_03_joint
  73: x_taxel_0_f2_prox_uSPa22_04_joint
  74: x_taxel_0_f3_prox_uSPa22_01_joint
  75: x_taxel_0_f3_prox_uSPa22_02_joint
  76: x_taxel_0_f4_prox_uSPa22_03_joint
  77: x_taxel_0_f4_prox_uSPa22_04_joint
  78: x_taxel_0_f1_dg5f_ft_12_joint
  79: x_taxel_0_f1_dg5f_ft_10_joint
  80: x_taxel_0_f1_dg5f_ft_05_joint
  81: x_taxel_0_f1_dg5f_ft_04_joint
  82: x_taxel_0_f1_dg5f_ft_02_joint
  83: x_taxel_0_f1_dg5f_ft_01_joint
  84: x_taxel_0_f2_prox_uSPa22_01_joint
  85: x_taxel_0_f2_prox_uSPa22_02_joint
  86: x_taxel_0_f4_prox_uSPa22_01_joint
  87: x_taxel_0_f4_prox_uSPa22_02_joint
  88: x_taxel_0_f5_prox_uSPa22_03_joint
  89: x_taxel_0_f5_prox_uSPa22_04_joint
  90: x_taxel_0_f5_prox_uSPa22_01_joint
  91: x_taxel_0_f5_prox_uSPa22_02_joint
  92: x_taxel_0_f1_mid_uSPa22_03_joint
  93: x_taxel_0_f1_mid_uSPa22_04_joint
  94: x_taxel_0_f1_mid_uSPa22_01_joint
  95: x_taxel_0_f1_mid_uSPa22_02_joint
  96: x_taxel_0_palm_uSPa46_19_joint
  97: x_taxel_0_palm_uSPa46_20_joint
  98: x_taxel_0_palm_uSPa46_21_joint
  99: x_taxel_0_palm_uSPa46_22_joint
  100: x_taxel_0_palm_uSPa46_23_joint
  101: x_taxel_0_palm_uSPa46_24_joint
  102: x_taxel_0_palm_uSPa46_13_joint
  103: x_taxel_0_palm_uSPa46_14_joint
  104: x_taxel_0_palm_uSPa46_15_joint
  105: x_taxel_0_palm_uSPa46_16_joint
  106: x_taxel_0_palm_uSPa46_17_joint
  107: x_taxel_0_palm_uSPa46_18_joint
  108: x_taxel_0_f1_prox_uSPa22_03_joint
  109: x_taxel_0_f1_prox_uSPa22_04_joint
  110: x_taxel_0_palm_uSPa46_07_joint
  111: x_taxel_0_palm_uSPa46_08_joint
  112: x_taxel_0_palm_uSPa46_09_joint
  113: x_taxel_0_palm_uSPa46_10_joint
  114: x_taxel_0_palm_uSPa46_11_joint
  115: x_taxel_0_palm_uSPa46_12_joint
  116: x_taxel_0_f1_prox_uSPa22_01_joint
  117: x_taxel_0_f1_prox_uSPa22_02_joint
  118: x_taxel_0_palm_uSPa46_01_joint
  119: x_taxel_0_palm_uSPa46_02_joint
  120: x_taxel_0_palm_uSPa46_03_joint
  121: x_taxel_0_palm_uSPa46_04_joint
  122: x_taxel_0_palm_uSPa46_05_joint
  123: x_taxel_0_palm_uSPa46_06_joint
