/**:
  ros__parameters:
    in_topic: /x_taxel_2f
    out_topic: markers
    frame_id: world
    frame_prefix: ""
    model_name: uSPr2F
    viz_mode: grid
    overlay_grid_in_urdf: false
    urdf_left_force_x_sign: -1.0
    urdf_left_force_y_sign: 1.0
    urdf_right_force_x_sign: -1.0
    urdf_right_force_y_sign: 1.0

    joint_states_mode: local
    global_joint_states_topic: /joint_states
    local_joint_states_topic: joint_states

    grid_rows: 4
    grid_cols: 6
    cell_size: 0.015
    module_gap: 0.04
    origin_x: 0.0
    origin_y: 0.0

    left_module_index: 0
    right_module_index: 1
    row_flip_right: true
    col_flip_right: true

    force_scale: 1.0
    max_force: 0.02
    use_fz_only: false
    use_xy_direction: true
    baseline_duration_sec: 3.0
    baseline_deadband_xy: 0.01
    baseline_deadband_z: 0.05
    baseline_deadband_taxel_xy: 10.0
    baseline_deadband_taxel_z: 60.0
    use_axis_normalization: true
    xy_force_range: 0.8
    z_force_range: 14.0
    use_taxels_when_no_forces: true
    xy_taxel_range: 1350.0
    z_taxel_range: 10085.0
    urdf_taxel_scale: 0.2

    use_cell_scale: true
    circle_area_scale: 2.0
    circle_height: 0.002

    arrow_length_scale: 2.0
    arrow_shaft_diameter: 0.001
    arrow_head_diameter: 0.002
    arrow_head_length: 0.003
    min_marker_scale: 0.0001

    grid_thickness: 0.0008
    grid_lines_enabled: true
    grid_line_width: 0.0005
    grid_line_alpha: 0.2
    grid_line_color: [0.2, 0.2, 0.2]

    grid_alpha: 1.0
    circle_alpha: 0.9
    arrow_alpha: 1.0
    debug_touch_stats: false

    grid_color: [0.91, 0.89, 0.86]
    style_preset: default
    color_low: [0.2, 0.4, 1.0]
    color_high: [1.0, 0.2, 0.2]
    marker_stamp_mode: now
    marker_time_offset_sec: -0.12
    left_force_x_sign: 1.0
    left_force_y_sign: -1.0
    right_force_x_sign: -1.0
    right_force_y_sign: 1.0
