pattern:
  rows: 31
  cols: 26
  index_map:
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 83
    - 101
    - -1
    - -1
    - -1
    - -1
    - -1
    - 185
    - 203
    - -1
    - -1
    - -1
    - -1
    - -1
    - 303
    - 329
    - -1
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 66
    - 84
    - 102
    - 123
    - -1
    - -1
    - -1
    - 164
    - 186
    - 204
    - 221
    - -1
    - -1
    - -1
    - 278
    - 304
    - 330
    - 347
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 62
    - 67
    - 85
    - 103
    - 124
    - 144
    - -1
    - 156
    - 165
    - 187
    - 205
    - 222
    - 246
    - -1
    - 266
    - 279
    - 305
    - 331
    - 348
    - 364
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 63
    - 68
    - 86
    - 104
    - 125
    - 145
    - -1
    - 157
    - 166
    - 188
    - 206
    - 223
    - 247
    - -1
    - 267
    - 280
    - 306
    - 332
    - 349
    - 365
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 64
    - 69
    - 87
    - 105
    - 126
    - 146
    - -1
    - 158
    - 167
    - 189
    - 207
    - 224
    - 248
    - -1
    - 268
    - 281
    - 307
    - 333
    - 350
    - 366
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 65
    - 70
    - 88
    - 106
    - 127
    - 147
    - -1
    - 159
    - 168
    - 190
    - 208
    - 225
    - 249
    - -1
    - 269
    - 282
    - 308
    - 334
    - 351
    - 367
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 71
    - 89
    - 107
    - 128
    - -1
    - -1
    - -1
    - 169
    - 191
    - 209
    - 226
    - -1
    - -1
    - -1
    - 283
    - 309
    - 335
    - 352
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 72
    - 90
    - 108
    - 129
    - -1
    - -1
    - -1
    - 170
    - 192
    - 210
    - 227
    - -1
    - -1
    - -1
    - 284
    - 310
    - 336
    - 353
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 73
    - 91
    - 109
    - 130
    - -1
    - -1
    - -1
    - 171
    - 193
    - 211
    - 228
    - -1
    - -1
    - -1
    - 285
    - 311
    - 337
    - 354
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 74
    - 92
    - 110
    - 131
    - -1
    - -1
    - -1
    - 172
    - 194
    - 212
    - 229
    - -1
    - -1
    - -1
    - 286
    - 312
    - 338
    - 355
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 75
    - 93
    - 111
    - 132
    - -1
    - -1
    - -1
    - 173
    - 195
    - 213
    - 230
    - -1
    - -1
    - -1
    - 287
    - 313
    - 339
    - 356
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 76
    - 94
    - 112
    - 133
    - -1
    - -1
    - -1
    - 174
    - 196
    - 214
    - 231
    - -1
    - -1
    - -1
    - 288
    - 314
    - 340
    - 357
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 77
    - 95
    - 113
    - 134
    - -1
    - -1
    - -1
    - 175
    - 197
    - 215
    - 232
    - -1
    - -1
    - -1
    - 289
    - 315
    - 341
    - 358
    - -1
  - - -1
    - -1
    - 17
    - 31
    - -1
    - -1
    - -1
    - 78
    - 96
    - 114
    - 135
    - -1
    - -1
    - -1
    - 176
    - 198
    - 216
    - 233
    - -1
    - -1
    - -1
    - 290
    - 316
    - 342
    - 359
    - -1
  - - -1
    - 4
    - 18
    - 32
    - 45
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
  - - 0
    - 5
    - 19
    - 33
    - 46
    - 58
    - -1
    - 79
    - 97
    - 115
    - 136
    - -1
    - -1
    - -1
    - 177
    - 199
    - 217
    - 234
    - -1
    - -1
    - -1
    - 291
    - 317
    - 343
    - 360
    - -1
  - - 1
    - 6
    - 20
    - 34
    - 47
    - 59
    - -1
    - 80
    - 98
    - 116
    - 137
    - -1
    - -1
    - -1
    - 178
    - 200
    - 218
    - 235
    - -1
    - -1
    - -1
    - 292
    - 318
    - 344
    - 361
    - -1
  - - 2
    - 7
    - 21
    - 35
    - 48
    - 60
    - -1
    - 81
    - 99
    - 117
    - 138
    - -1
    - -1
    - -1
    - 179
    - 201
    - 219
    - 236
    - -1
    - -1
    - -1
    - 293
    - 319
    - 345
    - 362
    - -1
  - - 3
    - 8
    - 22
    - 36
    - 49
    - 61
    - -1
    - 82
    - 100
    - 118
    - 139
    - -1
    - -1
    - -1
    - 180
    - 202
    - 220
    - 237
    - -1
    - -1
    - -1
    - 294
    - 320
    - 346
    - 363
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
  - - -1
    - 9
    - 23
    - 37
    - 50
    - -1
    - -1
    - -1
    - -1
    - 119
    - 140
    - 148
    - 152
    - 160
    - 181
    - -1
    - -1
    - 238
    - 250
    - 258
    - 270
    - 295
    - 321
    - -1
    - -1
    - -1
  - - -1
    - 10
    - 24
    - 38
    - 51
    - -1
    - -1
    - -1
    - -1
    - 120
    - 141
    - 149
    - 153
    - 161
    - 182
    - -1
    - -1
    - 239
    - 251
    - 259
    - 271
    - 296
    - 322
    - -1
    - -1
    - -1
  - - -1
    - 11
    - 25
    - 39
    - 52
    - -1
    - -1
    - -1
    - -1
    - 121
    - 142
    - 150
    - 154
    - 162
    - 183
    - -1
    - -1
    - 240
    - 252
    - 260
    - 272
    - 297
    - 323
    - -1
    - -1
    - -1
  - - -1
    - 12
    - 26
    - 40
    - 53
    - -1
    - -1
    - -1
    - -1
    - 122
    - 143
    - 151
    - 155
    - 163
    - 184
    - -1
    - -1
    - 241
    - 253
    - 261
    - 273
    - 298
    - 324
    - -1
    - -1
    - -1
  - - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
  - - -1
    - 13
    - 27
    - 41
    - 54
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 242
    - 254
    - 262
    - 274
    - 299
    - 325
    - -1
    - -1
    - -1
  - - -1
    - 14
    - 28
    - 42
    - 55
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 243
    - 255
    - 263
    - 275
    - 300
    - 326
    - -1
    - -1
    - -1
  - - -1
    - 15
    - 29
    - 43
    - 56
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 244
    - 256
    - 264
    - 276
    - 301
    - 327
    - -1
    - -1
    - -1
  - - -1
    - 16
    - 30
    - 44
    - 57
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - 245
    - 257
    - 265
    - 277
    - 302
    - 328
    - -1
    - -1
    - -1
