xela_taxel_viz_2f:
  ros__parameters:
    grid_rows: 4
    grid_cols: 8
    row_flip_right: false
    col_flip_right: false
    grid_index_map_left:
      - -1
      - 4
      - 0
      - 10
      - 14
      - 18
      - 22
      - 26
      - 8
      - 5
      - 1
      - 11
      - 15
      - 19
      - 23
      - 27
      - 9
      - 6
      - 2
      - 12
      - 16
      - 20
      - 24
      - 28
      - -1
      - 7
      - 3
      - 13
      - 17
      - 21
      - 25
      - 29
    grid_index_map_right:
      - 26
      - 22
      - 18
      - 14
      - 10
      - 0
      - 4
      - -1
      - 27
      - 23
      - 19
      - 15
      - 11
      - 1
      - 5
      - 8
      - 28
      - 24
      - 20
      - 16
      - 12
      - 2
      - 6
      - 9
      - 29
      - 25
      - 21
      - 17
      - 13
      - 3
      - 7
      - -1
    grid_separator_cols_left: [3]
    grid_separator_cols_right: [5]
