export function createAppState(config) {
  return {
    ws: null,
    connected: false,
    payload: null,
    lastReceivedMs: 0,
    activeWsUrl: null,
    uiMode: "grid",
    modeOverriddenByUser: false,
    requestedVizMode: "grid",
    sidecarRenderMode: "grid-2d",
    modelName: "",
    // DG-5F is right-hand-only, 5 fingers (f1..f5) + palm. Keyed directly by the
    // real module names from r_server_model_joint_map.yaml (no 2-digit code scheme like AH).
    showModules: {
      f1: true, f2: true, f3: true, f4: true, f5: true, palm: true,
      f1_dg5f_ft: true, f2_dg5f_ft: true, f3_dg5f_ft: true, f4_dg5f_ft: true, f5_dg5f_ft: true,
      f1_mid_uSPa22: true, f2_mid_uSPa22: true, f3_mid_uSPa22: true, f4_mid_uSPa22: true, f5_mid_uSPa22: true,
      f1_prox_uSPa22: true, f2_prox_uSPa22: true, f3_prox_uSPa22: true, f4_prox_uSPa22: true, f5_prox_uSPa22: true,
      palm_uSPa46: true,
    },
    sensorViewMode: "all",
    pendingSwitch: false,
    gridVectorMode: config.gridVectorMode || "xy",
    gridVectorZProjX: config.vector3dProjectX,
    gridVectorZProjY: config.vector3dProjectY,
    vectorEma: new Map(),
    lastStatsPaintMs: 0,
    lastStatsText: "",
    lastHintText: "",
    lastModeInfoText: "",
    camera: {
      yaw: 0.0,
      pitch: 0.0,
      zoom: 1.35,
      panX: 0.0,
      panY: 0.0,
    },
    drag: null,
    lastSceneExtent: 0.12,
    sourceTopicSubscribed: false,
    sourceByService: new Map(),
    sourceByServiceCallId: new Map(),
    serviceCallSeq: 0,
    urdfSources: {
      xela: {
        name: "xela",
        robotDescriptionTopic: config.xelaRobotDescriptionTopic,
        tfTopic: config.xelaTfTopic,
        tfStaticTopic: config.xelaTfStaticTopic,
        robotDescriptionService: config.xelaRobotDescriptionService,
        robotDescriptionXml: "",
        robotDescriptionVersion: 0,
        robotRootLink: "",
        tfEdges: new Map(),
        frameAliasCache: new Map(),
        pendingRobotDescriptionService: false,
        lastRobotDescriptionServiceReqMs: 0,
      },
      robot: {
        name: "robot",
        robotDescriptionTopic: config.robotRobotDescriptionTopic,
        tfTopic: config.robotTfTopic,
        tfStaticTopic: config.robotTfStaticTopic,
        robotDescriptionService: config.robotRobotDescriptionService,
        robotDescriptionXml: "",
        robotDescriptionVersion: 0,
        robotRootLink: "",
        tfEdges: new Map(),
        frameAliasCache: new Map(),
        pendingRobotDescriptionService: false,
        lastRobotDescriptionServiceReqMs: 0,
      },
    },
    lastRosbridgeErrorText: "",
    urdfRenderEpoch: 0,
    urdfMesh: {
      loading: false,
      ready: false,
      failed: false,
      failReason: "",
      THREE: null,
      renderer: null,
      scene: null,
      camera: null,
      controls: null,
      stlLoader: null,
      colladaLoader: null,
      rootGroup: null,
      robotGroup: null,
      markerGroup: null,
      linkGroups: new Map(),
      materialCache: new Map(),
      meshCache: new Map(),
      markerMap: new Map(),
      worldGrid: null,
      tfEdges: new Map(),
      frameAliasCache: new Map(),
      tfParentFrames: new Set(),
      linkModuleMap: new Map(),
      linkUrdfColorMap: new Map(),
      linkMeshMap: new Map(),
      activeModuleIds: new Set(),
      lastHighlightSignature: "",
      robotDescriptionXml: "",
      boundSourceName: "",
      boundRobotDescriptionVersion: -1,
      robotBuildToken: 0,
      robotBuilt: false,
      autoFrameDone: false,
      fixedFrame: config.defaultFixedFrame,
      tfFallbackActive: false,
      lastTfStats: null,
    },
  };
}
