export function createAppState(config) {
  return {
    ws: null,
    connected: false,
    payload: null,
    lastReceivedMs: 0,
    activeWsUrl: null,
    uiMode: "grid",
    modeOverriddenByUser: false,
    requestedVizMode: "grid",
    sidecarRenderMode: "grid-2d",
    modelName: "",
    pendingSwitch: false,
    gridVectorMode: config.gridVectorMode || "xy",
    gridVectorZProjX: config.vector3dProjectX,
    gridVectorZProjY: config.vector3dProjectY,
    vectorEma: new Map(),
    lastStatsPaintMs: 0,
    lastStatsText: "",
    lastHintText: "",
    lastModeInfoText: "",
    camera: {
      yaw: 0.0,
      pitch: 0.0,
      zoom: 1.35,
      panX: 0.0,
      panY: 0.0,
    },
    drag: null,
    lastSceneExtent: 0.12,
    sourceTopicSubscribed: false,
    sourceByService: new Map(),
    sourceByServiceCallId: new Map(),
    serviceCallSeq: 0,
    urdfSources: {
      xela: {
        name: "xela",
        robotDescriptionTopic: config.xelaRobotDescriptionTopic,
        tfTopic: config.xelaTfTopic,
        tfStaticTopic: config.xelaTfStaticTopic,
        robotDescriptionService: config.xelaRobotDescriptionService,
        robotDescriptionXml: "",
        robotDescriptionVersion: 0,
        robotRootLink: "",
        tfEdges: new Map(),
        frameAliasCache: new Map(),
        pendingRobotDescriptionService: false,
        lastRobotDescriptionServiceReqMs: 0,
      },
      robot: {
        name: "robot",
        robotDescriptionTopic: config.robotRobotDescriptionTopic,
        tfTopic: config.robotTfTopic,
        tfStaticTopic: config.robotTfStaticTopic,
        robotDescriptionService: config.robotRobotDescriptionService,
        robotDescriptionXml: "",
        robotDescriptionVersion: 0,
        robotRootLink: "",
        tfEdges: new Map(),
        frameAliasCache: new Map(),
        pendingRobotDescriptionService: false,
        lastRobotDescriptionServiceReqMs: 0,
      },
    },
    lastRosbridgeErrorText: "",
    urdfRenderEpoch: 0,
    urdfMesh: {
      loading: false,
      ready: false,
      failed: false,
      failReason: "",
      THREE: null,
      renderer: null,
      scene: null,
      camera: null,
      controls: null,
      stlLoader: null,
      colladaLoader: null,
      rootGroup: null,
      robotGroup: null,
      markerGroup: null,
      linkGroups: new Map(),
      materialCache: new Map(),
      meshCache: new Map(),
      markerMap: new Map(),
      worldGrid: null,
      tfEdges: new Map(),
      frameAliasCache: new Map(),
      tfParentFrames: new Set(),
      robotDescriptionXml: "",
      boundSourceName: "",
      boundRobotDescriptionVersion: -1,
      robotBuildToken: 0,
      robotBuilt: false,
      autoFrameDone: false,
      fixedFrame: config.defaultFixedFrame,
      tfFallbackActive: false,
      lastTfStats: null,
    },
  };
}
